USE [PSI20M_GiuliaTorres_2220119]

--**--**--**--**--**--**--** CATEGORIAS **--**--**--**--**--**--**--
INSERT INTO Categorias(
	id,
	nome)
VALUES(1,'Anime'),
(2,'Bebidas espirituosas'),
(3,'Brinquedos'),
(4,'Casa e decoração'),
(5,'Concertos'),
(6,'Desporto'),
(7,'Figuras Colecionáveis'),
(8,'Filmes e séries'),
(9,'Flores'),
(10,'Gadgets'),
(11,'Games'),
(12,'Jogos de tabuleiro'),
(13,'Joias'),
(14,'Livros'),
(15,'Maquilhagem'),
(16,'Musica'),
(17,'Papelaria'),
(18,'Peluches'),
(19,'Perfumes'),
(20,'Vegan')

SELECT *
FROM Categorias

--**--**--**--**--**--**--** Concelhos **--**--**--**--**--**--**--
INSERT INTO Concelhos(
	id,
	nome)
VALUES (1,'Amadora'),
(2,'Arruda dos Vinhos'),
(3,'Azambuja'),
(4,'Cascais'),
(5,'Lisboa'),
(6,'Loures'),
(7,'Lourinhã'),
(8,'Mafra'),
(9,'Odivelas'),
(10,'Oeiras'),
(11,'Sintra')

SELECT * 
FROM Concelhos

--**--**--**--**--**--**--** Vendedores **--**--**--**--**--**--**--
INSERT INTO Vendedores
VALUES
(1,'AllMovies',	5),
(2,'Ana artesanatos',1),
(3,'BeautyUp',8),
(4,'Bricolage Lisboeta',10),
(5,'CrisBeauty',2),
(6,'DrinkIt',7),
(7,'FitLift',	9),
(8,'GeekArea',	7),
(9,'GeekBoom',	5),
(10,'GrabIt',	10),
(11,'Joaquim flores',	6),
(12	,'Márcio joias',	11),
(13	,'Master of Things',	3),
(14	,'MoreRecords',	6),
(15	,'Nerdcoolness',	3),
(16	,'Os amores',	1),
(17	,'PapersOfLove',	4),
(18	,'TecTrack',	4),
(19	,'TicketsInLine',	11),
(20	,'ToysForFun',	3),
(21	,'Tudo para crianças',	5),
(22	,'Universe of Games',	9),
(23	,'ZezinhoMakeup',	8)

SELECT *
FROM Vendedores

--**--**--**--**--**--**--** Produtos **--**--**--**--**--**--**--

INSERT INTO Produtos
VALUES 
--(1,	'A História Oculta da Música',	16	,'Livro história da música',	9.8)
(2,	'A Raridade das Coisas Banais',	16	,'Autor: Pedro chagas Freitas',	24.9),
(3,	'Almofada Sailor Moon: Luna',	9	,'Almofaca 12cm Sailor Moon',	19.99),
(4,	'AM - LP',	14	,'Vinil Artic Monkeys',	29.99),
(5,	'Amor e Gelato',	16	,'sexta edição',	24.89),
(6,	'Benefit cosmetics Betint',	3	,'Batom gloss',	20.9),
(7,	'Brincos Harry Potter, Golden Snitch',	12	,'Brinco Harry Potter ouro',	59.00),
(8,	'Bubbles Concerto',	17	,'Concerto bubbles Sintra',	44.00),
(9,	'Bule preto e dourado 0,8 l SENDAI',	2	,'Bule chá preto e dourado, pedra pintado a mão',	34.99),
(10,	'Bush Baby World - Peluche com Cápsula (vários modelos)',	20	,'Peluche coleho surpresa',	24.99),
(11,	'Caderno Diário Wellness Designworks Ink - Take Care',	17	,'Caderno aros Good Vibes',	20.8),
(12,	'Caderno Inteligente A5 Butterfly',	13	,'Caderno inteligente capa colorida',	22.5),
(13,	'Caderno Pautado A5 Camurça Vegan Designworks Ink',	5	,'Caderno Vegano tecido carmuça A5',	25.4),
(14,	'Caderno Pautado Designworks Ink',	17	,'Caderno pautado Harry potter',	22.9),
(15,	'Caneca SUPERPLAY INTERNATIONAL Playstation - Comando',	22,'',		14.99),
(16,	'Caneta Pena Bloom',	13	,'Caneta esferiográfica Pena',	9.5),
(17,	'Castiçal dourado 11,5x14 cm SWAN',	2	,'Castiçal dourado geométrico',	12.99),
(18,	'Catan - O Jogo',	15	,'Jogo de tabuleiro estratégico',	38.24),
(19,	'Chapéu de Trekking na montanha', 	7	,'',	6),
(20,	'COLCHÃO DE TREKKING ULTRALIGHT S.I. AUTOINSUFLÁVEL',	7	,'',	67.9),
(21,	'conjunto colar e brincos Elevated Heart Rose',	12	,'Conjunto colar e brincos prata rose',	150.99),
(22,	'Conjunto de pastelaria BAKERY',	4	,'Kit 4 espátulas, forma, molde cupcakes e rolo de massa',	24.99),
(23,	'Conta Pendente Marvel The Avengers, Black Widow',	1	,'Adereço para pulseiras Avengers',	59.00),
(24,	'Conta Star Wars Grogu',	12	,'Adereço para pulseiras Star wars',	59.00),
(25,	'Demon Slayer - Livro 7: Combate Enclausurado',	16	,'',	22.00),
(26,	'Dino Friend',	17	,'Venha visitar dino e seus amigos',	21.35),
(27,	'Dior jadore',	12	,'',	60.41),
(28,	'Dior Sauvage',	5	,'',	70.72),
(29,	'Dixit Classic',	15	,'Jogo de tabuleiro estratégico',	29.71),
(30,	'Esferográfica Slim em Metal Designworks Ink',	17	,'4 Pack esferiográficas',	13.75),
(31,	'Eu Já Devia Saber',	16	,'Autora: Barbara Corby',	17.32),
(32,	'FAO Schwarz - Peluche Ursinho Soldado',	21	,'Peluche Urso soldado 38 cm',	39.99),
(33,	'Far Cry 6 - Yara Edition - PS4',	22	,'Jogo consola PS4', 	29.99),
(34,	'Figura Animatronica The Mandalorian - The Child',	21	,'Figura animatronica The Mandalorian',	80.00),
(35,	'Figura Marvel Vs. - Thor',	1	,'Figura realista colecionável', 	55.00),
(36,	'Fire Emblem Warriors: Three Hopes Edição Especial - Nintendo Switch',	22	,'Jogo consola Nintendo Switch',	19.99),
(37,	'Fisher Price - Imaginext - Batmobile e mota DC Super Friends',	20	,'Brinquedo super-herois',	47.9),
(38,	'Fortnite - Zoey - Porta-chaves POP Pocket',	8	,'Porta-chaves Fortnite',	9.00),
(39,	'Funko Peluche: Harry Potter Holiday - Hedwig 4',	21	,'Peluche Harry Potter',	13.99),
(40,	'Funko pop Bianca Belais',	8	,'',	19.9),
(41,	'Funko pop Harry Potter (quidditch)',	8	,'',	27.9),
(42,	'Funko pop Hello Kitty',	9	,'',	19.9),
(43,	'Funko pop Iron Man Avengers',	9	,'',	23.9),
(44,	'Funko pop pin Jerry Seinfeld', 	8	,'',	19.9),
(45,	'Funko Pop! Pokémon S5 - Pikachu 10',	8	,'Figura colecionável POP Pokemón',	25.9),
(46,	'GIFTSET Family Always Encircled',	12	,'Conjunto colar e brincos prata',	118.8),
(47,	'Gin Bombay Original', 	6	,'',	16.49),
(48,	'Gin Gordons',	6	,'',	12.99),
(49,	'Heartstopper - Livro 4: Muito Mais do Que Palavras',	16	,'Livro heartstopper',	12.39),
(50,	'Huda Beauty Color Block Obsessions', 	3	,'Paleta 9 sombras',	69.00),
(51,	'Hugo Boss Bottled Marine',	5	,'',	67.83),
(52,	'Jarra cinza 16x14x21cm FANTASY',	4	,'Jarra cinzenta Moderna',	19.99),
(53,	'Jewelcase CD',	14	,'CD Adele',	17.99),
(54,	'Jogo de Quebra-Cabeças HASBRO Jenga', 	15	,'',	19.79),
(55,	'Jogo HASBRO Twister',	15	,'',	18.91),
(56,	'Jogo Nintendo Switch Animal Crossing: New Horizons',	22	,'',	59.9),
(57,	'Jogo Nintendo Switch Donkey Kong Country - Tropical Freeze',	22	,'',	51.99),
(58,	'John Thompsons Easiest Piano Course Part 2',	14	,'CD aula piano',	6.49),
(59,	'Just Dance 2022 - Nintendo SwitchNintendo',	22	,'Jogo consola Nintendo Switch',	29.99),
(60,	'KDV beauty tattoo liner',	5	,'KVD eyeliner',	21.9),
(61,	'Lancôme LC idole',	5	,'',	43.12),
(62,	'LANTERNA FRONTAL DE TRAIL RUNNING ONNIGHT 710 300 LÚMENES PRETO E LARANJA',	18	,'Lanterna para cabeça preta e laranja',	33.5),
(63,	'Licor Beirão',	6	,'',	10.49),
(64,	'My Girl Tranças',	20	,'Boneca 35 cm',	20.00),
(65,	'Nars afia lápis', 	23	,'Afia para lápis de maquiagem', 	23.59),
(66,	'Natasha Denona Glam Palette',	23	,'Paleta 15 sombras',	19.59),
(67,	'Óculos de sol de caminhada - MH120 - adulto - categoria 3',	7	,'Óculos de sol adulto camihada', 	15.00),
(68,	'Panda e os Caricas', 	17	,'Concerto Panda e os caricas Sintra',	32.9),
(69,	'Paraíso',	16	,'Livro paraíso quarta edição', 	17.96),
(70,	'Party & Company Extreme 3.0',	15	,'Jogo de tabuleiro',	31.44),
(71,	'Peluche Marioneta Totoro do meu vizinho Totoro',	21	,'Peluche 30 cm Totoro',	27.99),
(72,	'Peluche PANDA Panda (Gigante)',	20	,'',	29.8),
(73,	'Prancha de Bodyboard Tandem Criança/Adulto',	7	,'',	35.00),
(74,	'Pulseira Moments Marvel The Avengers Logo',	1	,'Adereço para pulseiras Avengers',	59.00),
(75,	'RAMO DE FLORES CAMPESTRES',	11	,'Flores campestres aleatórias',	34.4),
(76,	'RAMO DE TULIPAS CAMPESTRE',	11	,'Ramo de flores feito com tulipas e ramos',	74.6),
(77,	'Raquete de Padel BP10 21 Adulto',	7,	'',	70.9),
(78,	'Rare beauty positive light',	5	,'Iluminador líquido', 	17.45),
(79,	'Rare beauty Soft Pinch',	3	,'Blush liquido',	33.9),
(80,	'Recomeçar - Limitado - Digipack CD',	14	,'Disco Vinil Recomeçar',	14.99),
(81,	'SINTRA LEGENDS | UNDERGROUND EXPERIENCE',	17	,'Concerto Legends Sintra',	70.00),
(82,	'SMARTWATCH DE CORRIDA COM GPS GARMIN FORERUNNER 45 PRETO',	18	,'Smartwatch corrida preto respirável',	140.3),
(83,	'Softshell Corta-vento Trekking Montanha', 	7	,''	,60.00),
(84,	'Spy x Family - Livro 3',	16	,'Livro Spy',	8.99),
(85,	'Tapete mouse Gaming Azul',	18	,'Tapete rato',	13.59),
(86,	'Tequila Casamigos Reposados',	6	,''	,77.89),
(87,	'Tequila Tiscaz',	10	,''	,16.49),
(88,	'TOALHA PONCHO XXL SURF 190x190 CM',	7	,'Toalha tipo poncho surf',	25.00),
(89,	'TOO faced chocolate soleil bronze',	5	,'Bronzer',	34.9),
(90,	'Too faced Lip Injection Maximum Plump',	23	,'Batom para crescer labios',	30.5),
(91,	'Totto - Mochila escolar adaptável a estrutura com rodas Acuareles Sprayl',	13	,'Mala Ajustável azul',	55.00),
(92,	'Urban decay all nighter setting spray',	5	,'Spray fixador',	21.9),
(93,	'Violeta',	16	,'Livro Violeta segunda edição',	5.99),
(94,	'Vodka Miss Silver',	10	,'',	5.99),
(95,	'Whisky Grants',	10, ''		,15.16),
(96,	'Whisky Passport',	6,	''	,9.99),
(97,	'Yves Saint Laurent',	23	,'Perfume Yves Saint Laurent 60ml',	51.4),
(98,	'Zoeva infinite potential',	3	,'Máscara de pestanas',	12.49)
